version: '3.9'
services:
  auth-ms:
    build: ./auth-ms
    networks:
      - backend
  contests-ms:
    build: ./contests-ms
    networks:
      - backend
  challenges-ms:
    build: ./challenges-ms
    networks:
      - backend
  submissions-ms:
    build: ./submissions-ms
    networks:
      - backend
  mail-sender:
    build: 
      context: ./mail-sender
      args:
        QUEUE_NAME: email_queue
        REDIS_HOST: redis
        REDIS_PORT: 6379
    networks:
      - backend
  api-gateway:
    ports:
      - "8000:8765"
    build: 
      context: ./api-gateway
      args:
        SUBMISSIONS_MS_HOST_PORT: submissions-ms:80
        AUTH_MS_HOST_PORT: auth-ms:80
        CONTESTS_MS_HOST_PORT: contests-ms:80
        CHALLENGES_MS_HOST_PORT: challenges-ms:80
    networks:
      - frontend
      - backend
  frontend:
    build: 
      context: ./frontend
      args:
        API_GATEWAY_HOST_PORT: localhost:8000
    ports:
      - "8080:3000"
    networks:
      - frontend
  redis:
    image: redis:latest
    networks:
      - backend



networks:
  frontend:
  backend: